DELETE http://localhost:8080/ingredients/all


###
PUT http://localhost:8080/ingredients/0
Content-Type: application/json

{
  "title": "Пшеничная мукка",
  "count": 6,
  "measureUnit": "ст. л."
}


###
GET http://localhost:8080/ingredients/all

###
POST http://localhost:8080/ingredients
Content-Type: application/json

{
  "title": "Пшеничная мука",
  "count": 6,
  "measureUnit": "ст. л."
}


###
POST http://localhost:8080/recipes
Content-Type: application/json

{
  "title": "Сырники из творога",
  "cookingTime": 30,
  "ingredients": [
    {
      "title": "Творог",
      "count": 350,
      "measureUnit": "г."
    },
    {
      "title": "Куриное яйцо",
      "count": 2,
      "measureUnit": "шт."
    },
    {
      "title": "Пшеничная мука",
      "count": 6,
      "measureUnit": "ст. л."
    }
  ],
  "steps": ["Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте." , "Всыпьте в творог муку и тщательно перемешайте.", "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло.", "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду.", "Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния.", "Повторяйте, пока творог не закончится."]
}
###
POST http://localhost:8080/recipes/search
Content-Type: application/json

[
    {
      "title": "Творог",
      "count": 350,
      "measureUnit": "г."
    },
    {
      "title": "Куриное яйцо",
      "count": 2,
      "measureUnit": "шт."
    }
 ]

###
DELETE http://localhost:8080/ingredients/all


###
PUT http://localhost:8080/recipes/0
Content-Type: application/json

{
  "title": "Сырник из творога",
  "cookingTime": 30,
  "ingredients": [
    {
      "title": "Творог",
      "count": 350,
      "measureUnit": "г."
    },
    {
      "title": "Куриное яйцо",
      "count": 2,
      "measureUnit": "шт."
    },
    {
      "title": "Пшеничная мука",
      "count": 6,
      "measureUnit": "ст. л."
    }
  ],
  "steps": ["Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте." , "Всыпьте в творог муку и тщательно перемешайте.", "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло.", "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду.", "Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния.", "Повторяйте, пока творог не закончится."]
}

###
GET http://localhost:8080/recipes/?currentPage=1&pages=1


###
GET http://localhost:8080/recipes/search/0
